spring:
  datasource:
    batch:
      # H2 for Spring Batch metadata
      jdbc-url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
      name: TEST_H_DATASOURCE
    app:     # Postgres for business data
      jdbc-url: jdbc:postgresql://localhost:5432/mydb?currentSchema=public
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: mysecret
      name: TEST_H_TARGET

  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
